/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.ufc.view;

import br.com.ufc.exception.ANEException;
import br.com.ufc.exception.ENEException;
import br.com.ufc.exception.LJEException;
import br.com.ufc.exception.LLUException;
import br.com.ufc.exception.LNEException;
import br.com.ufc.main.Main;
import br.com.ufc.model.Aluno;
import br.com.ufc.model.Emprestimo;
import br.com.ufc.model.Livro;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rubens
 */
public class TelaEmprestimo extends javax.swing.JFrame {

    /**
     * Creates new form TelaEmprestimo
     */
    public TelaEmprestimo() {
        initComponents();
        this.setLocationRelativeTo(null);
        carregarTodos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfID = new javax.swing.JTextField();
        tfLivro = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfAluno = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbEmprestimos = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        idPesquisa = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jLabel1.setText("ID Empréstimo");

        jLabel2.setText("Livro (ISBN)");

        jLabel3.setText("Aluno (matrícula)");

        jButton1.setText("Concluir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tbEmprestimos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Livro", "Aluno", "Emprestado em", "Devolução"
            }
        ));
        jScrollPane1.setViewportView(tbEmprestimos);

        jLabel6.setText("ID Empréstimo");

        jButton2.setText("Devolver");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Renovar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 617, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(idPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(tfLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(tfAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3)
                    .addComponent(jButton2))
                .addGap(7, 7, 7))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void limparTabela() {
        DefaultTableModel model = (DefaultTableModel) tbEmprestimos.getModel();
        
        if (model.getRowCount() > 0) {
            for (int i = model.getRowCount() - 1; i > -1; i--) {
                model.removeRow(i);
            }
        }
    }
    
    public void carregarTodos() {
        DefaultTableModel model = (DefaultTableModel) tbEmprestimos.getModel();
        limparTabela();
        
        try {
            for(Emprestimo a : Main.emprestimoDao.buscarTodos()) {
                model.addRow(new Object[]{""+a.getNumeroEmprestimo(), a.getLivro().getTitulo(), a.getAluno().getNome(), new SimpleDateFormat("dd/MM/yyyy").format(a.getDataEmprestimo()), new SimpleDateFormat("dd/MM/yyyy").format(a.getDataDevolucao())});
            }
        } catch (ENEException ex) {
            JOptionPane.showMessageDialog(this, "A tabela esta vazia pois não existe nenhum empréstimo cadastrado.", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(tfID.getText().isEmpty() || tfLivro.getText().isEmpty() || tfAluno.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Preencha todos os campos!", "Erro", JOptionPane.ERROR_MESSAGE);
        } else {
            int idEmprestimo;
            try {
                idEmprestimo = Integer.parseInt(tfID.getText());
                try {
                    Main.emprestimoDao.buscarEmprestimo(idEmprestimo);
                    tfID.setText("");
                    tfID.requestFocus();
                    JOptionPane.showMessageDialog(this, "Já existe um empréstimo com este id!", "Erro", JOptionPane.ERROR_MESSAGE);
                } catch (ENEException ex) {
                    //Populando entidades
                    Livro livro = Main.livroDao.buscarLivro(Integer.parseInt(tfLivro.getText()));
                    Aluno aluno = Main.alunoDao.buscarAluno(Integer.parseInt(tfAluno.getText()));

                    Date dataAtual = new Date();

                    //Converte a data para Calendar
                    Calendar c = Calendar.getInstance();
                    c.setTime(dataAtual);

                    // Soma 15 dias
                    c.add(Calendar.DAY_OF_MONTH, 15);

                    //Converte de volta de Calendar para Date
                    Date dataDevolucao = c.getTime();

                    Emprestimo e = new Emprestimo();
                    
                    if(livro.getEmprestimo() != null) {
                        JOptionPane.showMessageDialog(this, "Este livro já está emprestado!", "Erro", JOptionPane.ERROR_MESSAGE);
                    } else {
                        if(aluno.getEmprestimos().size() == 4) {
                            JOptionPane.showMessageDialog(this, "Limite de empréstimo excedido para este aluno!", "Erro", JOptionPane.ERROR_MESSAGE);
                        } else {
                            e.setNumeroEmprestimo(idEmprestimo);
                            e.setLivro(livro);
                            livro.setEmprestimo(e);
                            aluno.getEmprestimos().add(e);
                            e.setAluno(aluno);
                            e.setDataEmprestimo(new Date());
                            e.setDataDevolucao(dataDevolucao);
                            e.setRenovacao(false); //Um empréstimo começa sem renovação
                            Main.emprestimoDao.emprestarLivro(e);
                            tfID.setText("");
                            tfLivro.setText("");
                            tfAluno.setText("");
                            tfID.requestFocus();
                            JOptionPane.showMessageDialog(this, "Empréstimo realizado", "Informação", JOptionPane.INFORMATION_MESSAGE);
                            carregarTodos(); //Carrega tabela
                        }
                    }
                }
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Você inseriu algum valor inválido!", "Erro", JOptionPane.ERROR_MESSAGE);
            } catch (LNEException ex) {
                tfLivro.setText("");
                tfLivro.requestFocus();
                JOptionPane.showMessageDialog(this, "Este livro não existe!", "Erro", JOptionPane.ERROR_MESSAGE);
            } catch (ANEException ex) {
                tfAluno.setText("");
                tfAluno.requestFocus();
                JOptionPane.showMessageDialog(this, "Este aluno não existe!", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int idEmprestimo;
        try {
            idEmprestimo = Integer.parseInt(idPesquisa.getText());
            Emprestimo e = Main.emprestimoDao.buscarEmprestimo(idEmprestimo);
            if(!e.isRenovacao()) { //Verifica se já foi renovado
                e.setRenovacao(true);
                Date dataAtual = e.getDataDevolucao();

                //Converte a data para Calendar
                Calendar c = Calendar.getInstance();
                c.setTime(dataAtual);

                // Soma 15 dias
                c.add(Calendar.DAY_OF_MONTH, 7);

                //Converte de volta de Calendar para Date
                Date dataDevolucao = c.getTime();
                e.setDataDevolucao(dataDevolucao);
                carregarTodos();
            } else {
                idPesquisa.setText("");
                idPesquisa.requestFocus();
                JOptionPane.showMessageDialog(this, "Este empréstimo já foi renovado.", "Erro", JOptionPane.ERROR_MESSAGE);
            }
            
        } catch(NumberFormatException ex) {
            idPesquisa.setText("");
            idPesquisa.requestFocus();
            JOptionPane.showMessageDialog(this, "Insira um valo válido", "Erro", JOptionPane.ERROR_MESSAGE);
        } catch (ENEException ex) {
            JOptionPane.showMessageDialog(this, "Este empréstimo não existe", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int idEmprestimo;
        try {
            idEmprestimo = Integer.parseInt(idPesquisa.getText());
            Emprestimo e = Main.emprestimoDao.buscarEmprestimo(idEmprestimo);
            e.getLivro().setEmprestimo(null);
            e.getAluno().getEmprestimos().remove(e);
            Main.emprestimoDao.devolverLivro(idEmprestimo);
            carregarTodos();
            idPesquisa.setText("");
            tfID.requestFocus();
            JOptionPane.showMessageDialog(this, "Livro devolvido", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
        } catch(NumberFormatException ex) {
            idPesquisa.setText("");
            idPesquisa.requestFocus();
            JOptionPane.showMessageDialog(this, "Insira um valor válido", "Erro", JOptionPane.ERROR_MESSAGE);
        } catch (ENEException ex) {
            JOptionPane.showMessageDialog(this, "Este empréstimo não existe", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaEmprestimo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField idPesquisa;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbEmprestimos;
    private javax.swing.JTextField tfAluno;
    private javax.swing.JTextField tfID;
    private javax.swing.JTextField tfLivro;
    // End of variables declaration//GEN-END:variables
}
